
enable:

disable:

override_nonhours:
  fields:
    hours:
      required: true
      example: 2

scheduler_set:
  fields:
    charge_amount:
      required: true
      example: 7.2
    departure_time:
      required: true
      example: 2022-06-02 07:00
    schedule_starttime:
      example: 2022-06-01 18:00
    override_settings:
      example: False

scheduler_cancel:

override_charge_amount:
  fields:
    desired_charge_amount:
      required: true
      example: 10

update_peaks_history:
  fields:
    import_dictionary:
      required: true
      example: "{'2021_1': 0.2, '2021_2': 0.3, '2021_3': 0.4}"

update_current_peaks:
  fields:
    import_dictionary:
      required: true
      example: "{'1h17': 2.35, '26h21': 2.29, '29h2': 3.7}"

